/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsPidRouteImport } from './routes/products.$pid'

const ProductsLazyRouteImport = createFileRoute('/products')()

const ProductsLazyRoute = ProductsLazyRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/products.lazy').then((d) => d.Route))
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPidRoute = ProductsPidRouteImport.update({
  id: '/$pid',
  path: '/$pid',
  getParentRoute: () => ProductsLazyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/products': typeof ProductsLazyRouteWithChildren
  '/products/$pid': typeof ProductsPidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/products': typeof ProductsLazyRouteWithChildren
  '/products/$pid': typeof ProductsPidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/products': typeof ProductsLazyRouteWithChildren
  '/products/$pid': typeof ProductsPidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/products' | '/products/$pid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/products' | '/products/$pid'
  id: '__root__' | '/' | '/about' | '/products' | '/products/$pid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProductsLazyRoute: typeof ProductsLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$pid': {
      id: '/products/$pid'
      path: '/$pid'
      fullPath: '/products/$pid'
      preLoaderRoute: typeof ProductsPidRouteImport
      parentRoute: typeof ProductsLazyRoute
    }
  }
}

interface ProductsLazyRouteChildren {
  ProductsPidRoute: typeof ProductsPidRoute
}

const ProductsLazyRouteChildren: ProductsLazyRouteChildren = {
  ProductsPidRoute: ProductsPidRoute,
}

const ProductsLazyRouteWithChildren = ProductsLazyRoute._addFileChildren(
  ProductsLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProductsLazyRoute: ProductsLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
